-- Use UI2
require('vim._core.ui2').enable({
    enable = true,
    msg = {
        targets = {
            [''] = 'msg',
            empty = 'msg',
            bufwrite = 'msg',
            confirm = 'msg',
            emsg = 'msg',
            echo = 'msg',
            echomsg = 'msg',
            echoerr = 'msg',
            completion = 'msg',
            list_msg = 'msg',
            lua_error = 'msg',
            lua_print = 'msg',
            progress = 'msg',
            rpc_error = 'msg',
            quickfix = 'msg',
            search_msg = 'msg',
            search_count = 'msg',
            shell_msg = 'msg',
            shell_err = 'msg',
            shell_out = 'msg',
            shell_ret = 'msg',
            undo = 'msg',
            verbose = 'msg',
            wildlist = 'msg',
            wmsg = 'msg',
            typed_msg = 'msg',
        },
    },
})
