return {
	fg = { 'Normal' },
	bg = { 'Normal:bg' },
	sub_fg = { 'Normal', 'NormalFloat' },
	sub_bg = { 'Normal:bg', 'NormalFloat:bg' },
	nontext_fg = { 'Normal', 'NonText' },
	comment = { 'Normal', 'Comment' },
	type = { 'Normal', 'Type' },
	func = { 'Normal', 'Function' },
	preproc = { 'Normal', 'PreProc' },
	special = { 'Normal', 'Special' },
	statement = { 'Normal', 'Statement' },
	constant = { 'Normal', 'Constant' },
	string = { 'Normal', 'String' },
	git_add = { 'Normal', 'Added', 'GitSignsAdd' },
	git_change = { 'Normal', 'Changed', 'GitSignsChange' },
	git_delete = { 'Normal', 'Removed', 'GitSignsDelete' },
	diag_error = { 'Normal', 'DiagnosticError' },
	diag_warn = { 'Normal', 'DiagnosticWarn' },
	diag_info = { 'Normal', 'DiagnosticInfo' },
	diag_hint = { 'Normal', 'DiagnosticHint' },
}
